### ISSUE TITLE
src

### ISSUE THREAD

**Issue by dekrypted** [MmCopyMemory/temp-spoof#3]
tryna drop src

**Comment by MmCopyMemory** [comment]
forgot about this repo lol, will drop source if I am bored enough and update it aswell

**Comment by dekrypted** [comment]
why cant u js drop the current one? but ya thats allg ty bro, its the only decent working one i found so far but i wanna make some changes

**Comment by dekrypted** [comment]
oh, btw do u got a discord i can talk to u at?

**Comment by KiExitDispatcher** [comment]
he got it

**Comment by dekrypted** [comment]
oh shit wsg codepulze

**Comment by coolboy0312** [comment]
he may have lost the sources

**Comment by KiExitDispatcher** [comment]
oh ye i forgot 💀 :
